#pragma once
enum States
{
	STATE_MAINMENU,
	STATE_ABOUT,
	STATE_HELP,
	STATE_SELECTADVENTURE,
	STATE_VIEWHALLOFFAME,
	STATE_GAMEPLAY,
	STATE_NEWHIGHSCORE,
	STATE_EXIT,
	STATE_NULL,
	GAME_MOUNTAINWORLD,
	GAME_WATERWORLD,
	GAME_BOXWORLD,
};